HiddenUnits = {
	"Orange Tabby",
	"Silver Tabby",
	"Bombay",
	"Cornish Rex",
	"Hawk Owl",
	"Great Horned Owl",
	"Cockatiel",
	"Senegal",
	"Black Kingsnake",
	"Brown Snake",
	"Crimson Snake",
	"Prairie Dog",
	"Cockroach",
	"Ancona Chicken",
	"Worg Pup",
	"Smolderweb Hatchling",
	"Mechanical Chicken",
	"Sprite Darter",
	"Green Wing Macaw",
	"Hyacinth Macaw",
	"Tiny Black Whelpling",
	"Tiny Emerald Whelpling",
	"Tiny Crimson Whelpling",
	"Siamese",
	"Unconscious Dig Rat",
	"Mechanical Squirrel",
	"Pet Bombling",
	"Lil' Smokey",
	"Lifelike Mechanical Toad",
	"Corrupted Blue Whelp",
	"Corrupted Bronze Whelp",
	"Corrupted Green Whelp",
	"Corrupted Red Whelp",
	"Razzashi Skitterer",
	"Razzashi Venombrood",
	"Spider","Snake",
	"Vekniss Drone",
	"Vekniss Hatchling",
}
